using System.Web;
using System.Web.Optimization;

namespace Popups
{
    public class BundleConfig
    {
        // For more information on bundling, visit https://go.microsoft.com/fwlink/?LinkId=301862
        public static void RegisterBundles(BundleCollection bundles)
        {
            bundles.Add(new ScriptBundle("~/bundles/jquery").Include(
                        "~/Scripts/jquery-{version}.js",
                        "~/Scripts/jquery-confirm.js",
                        "~/Scripts/jquery-ui-1.12.1.js"));

            bundles.Add(new ScriptBundle("~/bundles/jqueryval").Include(
                        "~/Scripts/jquery.validate*"));

            // Use the development version of Modernizr to develop with and learn from. Then, when you're
            // ready for production, use the build tool at https://modernizr.com to pick only the tests you need.
            bundles.Add(new ScriptBundle("~/bundles/modernizr").Include(
                        "~/Scripts/modernizr-*"));

            bundles.Add(new ScriptBundle("~/bundles/bootstrap").Include(
                      "~/Scripts/bootstrap.js"));

            bundles.Add(new ScriptBundle("~/bundles/autogenerated").Include(
                      "~/Autogenerated/init-data.js",
                      "~/Autogenerated/Models/action-execute-type.js",
                      "~/Autogenerated/Models/action-type.js",
                      "~/Autogenerated/Models/popup-color.js",
                      "~/Autogenerated/Models/popup-type.js",
                      "~/Autogenerated/Models/popup-model.js",
                      "~/Autogenerated/Models/IButtonModel.js",
                      "~/Autogenerated/Models/ButtonModel.js",
                      "~/Autogenerated/Models/ButtonRegistry.js"));

            bundles.Add(new StyleBundle("~/Content/css").Include(
                      "~/Content/bootstrap.css",
                      "~/Content/site.css",
                      "~/Content/jquery-confirm.css",
                      "~/node_modules/jqueryui/jquery-ui.css"));
        }
    }
}
